config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
end

app/controllers/home.rb
# frozen_string_literal: true

# HomeController
class HomeController < ApplicationController
  def index; end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

# StudentsController
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update]

  def index
    @students = Student.all
  end

  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :last_name, :maiden_name, :email, :phone, :mobile_phone, :city, :state, :zip_code, :street, :external_number, :internal_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/_sidenav.html.slim
/ nav.navbar.navbar-light.bg-light.fixed-top
/   .container-fluid
/     a.navbar-brand[href="#"]
/       | Offcanvas navbar
/     button.navbar-toggler[type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"]
/       span.navbar-toggler-icon
/     #offcanvasNavbar.offcanvas.offcanvas-end[tabindex="-1" aria-labelledby="offcanvasNavbarLabel"]
/       .offcanvas-header
/         h5#offcanvasNavbarLabel.offcanvas-title
/           | Offcanvas
/         button.btn-close.text-reset[type="button" data-bs-dismiss="offcanvas" aria-label="Close"]
/       .offcanvas-body
/         ul.navbar-nav.justify-content-end.flex-grow-1.pe-3
/           li.nav-item
/             a.nav-link.active[aria-current="page" href="#"]
/               | Home
/           li.nav-item
/             a.nav-link[href="#"]
/               | Link
/           li.nav-item.dropdown
/             a#offcanvasNavbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"]
/               |  Dropdown 
/             ul.dropdown-menu[aria-labelledby="offcanvasNavbarDropdown"]
/               li
/                 a.dropdown-item[href="#"]
/                   | Action
/               li
/                 a.dropdown-item[href="#"]
/                   | Another action
/               li
/                 hr.dropdown-divider
/               li
/                 a.dropdown-item[href="#"]
/                   | Something else here
/         form.d-flex
/           input.form-control.me-2[type="search" placeholder="Search" aria-label="Search"]
/           button.btn.btn-outline-success[type="submit"]
/             | Search

app/views/home/index.html.slim
h1 Hello world

app/views/layouts/_alert.html.slim
.col.alert.alert-warning.alert-dismissible.fade.show[role="alert"]
  strong
    = notice
  button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | UdepApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    / = render partial: 'home/sidenav'
    .container
      = yield

app/views/students/_form.html.slim
= form_with(model: @student) do |f|
  - if @student.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      ul
        - @student.errors.each do |error|
          li = error.full_message

  .row.form-group style='margin-bottom: 15px'
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :name, class: "form-control", placeholder: "name"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :last_name, class: "form-control", placeholder: "last name"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :maiden_name, class: "form-control", placeholder: "last name"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :email, class: "form-control", placeholder: "email"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :phone, class: "form-control", placeholder: "phone"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :mobile_phone, class: "form-control", placeholder: "mobile"
  .row.form-group style='margin-top: 15px'
    h1 Student Contact
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :city, class: "form-control", placeholder: "city"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :state, class: "form-control", placeholder: "state"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :zip_code, class: "form-control", placeholder: "zip_code"
    .col-xs-12.col-md-6 style='margin-bottom: 15px'
      = f.text_field :street, class: "form-control", placeholder: "street"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :external_number, class: "form-control", placeholder: "external_number"
    .col-xs-12.col-md-4 style='margin-bottom: 15px'
      = f.text_field :internal_number, class: "form-control", placeholder: "internal_number"

  .row.actions
    .col-lg-12.col-md-12.col-sm-12.col-xs-12.text-right
      = f.submit class: 'btn btn-primary'

app/views/students/_student.html.slim
div id="#{dom_id student}"
  p
    strong Name:
    =< student.name
  p
    strong Last name:
    =< student.last_name
  p
    strong Maiden name:
    =< student.maiden_name
  p
    strong Email:
    =< student.email
  p
    strong Phone:
    =< student.phone
  p
    strong Mobile phone:
    =< student.mobile_phone
  p
    strong City:
    =< student.city
  p
    strong State:
    =< student.state
  p
    strong Zip code:
    =< student.zip_code
  p
    strong Street:
    =< student.street
  p
    strong External number:
    =< student.external_number
  p
    strong Internal number:
    =< student.internal_number

app/views/students/edit.html.slim
h1 Editing student

== render "form", student: @student

br

div
  => link_to "Show this student", @student
  '|
  =< link_to "Back to students", students_path

app/views/students/index.html.slim
- @students.model
.row
  .col-lg-3.col-md-3.col-sm-12.col-xs-12
    h1 Students List
  .col-lg-3.col-md-3.col-sm-12.col-xs-12.text-right
    = link_to "New student", new_student_path, class: 'btn btn-primary'
  .row
    .col
      .container-fluid
        div.table-responsive
          table.table.table-striped.table-hover.table-borderless style="width: 100%;"
            thead.thead-inverse
              tr
                th style="width: 10%" Date
                th style="width: 8%" Name
                th style="width: 17%" Surname
                th style="width: 17%" city
                th style="width: 17%" Email
                th style="width: 15%" Mobile phone
                th style="width: 24%"
            tbody
              - @students.each do |student|
                tr
                  td style="width: 10%" = student.created_at
                  td style="width: 10%" = student.name
                  td style="width: 10%" = student.last_name
                  td style="width: 10%" = student.city
                  td style="width: 10%" = student.email
                  td style="width: 10%" = student.mobile_phone
                  td style="width: 24%"
                    = link_to 'Show', student_path(student.id), class: 'btn btn-default'
                    '
                    = link_to 'Edit', edit_student_path(student.id), class: 'btn btn-default'

/     == render student
/     p
/       = link_to "Show this student", student

/ = link_to "New student", new_student_path

app/views/students/new.html.slim
.container
  .row
    h1  New student
  = render 'form'

/ h1 New student

/ == render "form", student: @student

/ br

/ div
/   = link_to "Back to students", students_path

app/views/students/show.html.slim
== render @student

div
  => link_to "Edit this student", edit_student_path(@student)
  '|
  =< link_to "Back to students", students_path

  = button_to "Destroy this student", @student, method: :delete